# appveyor.yml
build: off

image: Ubuntu1804

clone_folder: /usr/go/src/github.com/ShiraazMoollatjie/devtogo

environment:
  GOPATH: /usr/go/

stack: go 1.13

before_test:
  - go vet ./...

test_script:
  - go test ./...